name: ArgoCD Sync

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Manifest Repo
      uses: actions/checkout@v3
      with:
        repository: prabhakar732/k8s-manifests
        token: ${{ secrets.REPO_TOKEN }}

    - name: Update Image Tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/springboot-ci-cd-demo:${{ github.sha }}|" k8s/deployment.yaml

    - name: Commit and Push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git commit -am "Update image to ${{ github.sha }}"
        git push
