name: Ascii Workflow

on: [push]

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Execute shell script
      run: |
        chmod +x ascii.sh
        ./ascii.sh
