name: Ascii Workflow

on: 
  workflow_dispatch:
    
env:
  name: AluriPrabhakar

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display environment variable
        run: echo "Variable name: ${{ env.name }}"

      - name: Execute shell script
        run: echo "Script is not available" > data.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upload-data
          path: data.txt

  ascii_job1:
    needs: ascii_job
    runs-on: ubuntu-latest
    steps:
      - name: Verify the job
        run: echo "Run the job" > data.txt

      - name: Display the data
        run: ls -l

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: upload-data
          path: .
