name: Ascii Workflow

on: [push]
env:
  name: AluriPrabhakar

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: display-env
        run: echo "varianle name: ${{name}}"
      - name: Execute shell script
        run: echo "Script is not available" > data.txt
      - name: upload artificate
        uses: actions/upload-artifact@v4
        with:
          name: upload-data
          path: data.txt

  ascii_job1:
    needs: ascii_job
    runs-on: ubuntu-latest
    steps:
      - name: verigy the job
        run: echo "run the job" > data.txt
      - name: display the data
        run: ls -l
      - name: download-artifict
        uses: actions/download-artifact@v4
        with:
          name: data.txt


