name: Deploy & Run the Databrics notebook

on:
  push:
    branches:
      - main

jobs:
  run-databrics-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Databrics CLI
        uses: PIP install databrics-cli

      - name: configure Databrics CLI
        run: |
          databrics configure --host ${{ secrets.DATABRICS_HOST }} --token ${{ secrets.DATABRICS_TOKEN }}

      - name: upload notebook to databris
        run: |
          databrics workspace import local_notebooks/sample_notebook.py /opt/sample_notebook --format SOURCE --overwrite

      - name: Run Databrics Notebook
        run:  |
            JOB_ID=$(databricks jobs create --json '{
            "name": "GitHub Action Job",
            "new_cluster": {
              "spark_version": "13.0.x-scala2.12",
              "node_type_id": "Standard_D3_v2",
              "num_workers": 2
            },
            "notebook_task": {
              "notebook_path": "/Users/my-user/sample_notebook"
            }
          }' | jq -r '.job_id')

          RUN_ID=$(databricks jobs run-now --job-id $JOB_ID | jq -r '.run_id')

          echo "Waiting for job completion..."
          databricks runs wait --run-id $RUN_ID
     - name: Get run output
       run: |
         databrics runs get-output --run-id $RUN_ID
