name: workflow2

on: [push]

jobs:
  first_job:
    runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: list and read the files
        run: |
          echo " My first github action"
          ls -lrth
          cat readme.txt

      - name: Generate Ascii at work
        run: cowsay -f dargon  " Run for cover, I am Dragon ...RAWR" >> dragon.txt
